version: '3'

services:
  frontend:
    build:
      context: ./projeto-front
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:3000
    ports:
      - "3001:3000"   

  backend:
    build:
      context: ./projeto-back
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
