version: '3'

services:
  frontend:
    image: frontend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:3000
    ports:
      - "3001:3000"

  backend:
    image: backend
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
