name: CI Pipeline Devops

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 

      - name: Build the Front Docker image
        run: docker build -t lucas8610/app:front-latest -f projeto-front/Dockerfile .

      - name: Push the Front image to Dockerhub
        run: docker push lucas8610/app:front-latest

      - name: Build the Back Docker image
        run: docker build -t lucas8610/app:back-latest -f projeto-back/Dockerfile .

      - name: Push the Back image to Dockerhub
        run: docker push lucas8610/app:back-latest
