name: CI deploy

on:
  push:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 

      - name: Build the Docker image
        run: docker build -t lucas8610/front:latest -f projeto-front/Dockerfile .

      - name: Push to Dockerhub
        run: docker push lucas8610/front:latest
