name: Docker front and back CI deploy

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build front Docker image
        run: |
          docker build -t front -f projeto-front/Dockerfile .
          docker images # Adiciona este comando para listar as imagens disponíveis localmente

      - name: Push front to Dockerhub
        run: docker push lucas8610/front:latest

      - name: Build back Docker image
        run: docker build -t back -f projeto-back/Dockerfile .

      - name: Push back to Dockerhub
        run: docker push lucas8610/back:latest
