name: Docker front CI deploy

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if Dockerfile exists
        run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -t lucas8610/front .

      - name: Push to Dockerhub
        run: docker push lucas8610/front:latest
