name: Docker front CI

on:
  push:
    branches: [ "staging" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t front . docker build -t back .
      
    - name: Push to Dockerhub 
      run: docker push lucas8610/front:latest docker push lucas8610/back:latest    
    
    
      