name: Deploy DevOps 

on:
    push:
        branches: [staging]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
